### ISSUE TITLE
KDE: Not using the correct GTK theme

### ISSUE THREAD

**Issue by Bleuzen** [flatpak/flatpak#1147]
Hi, I installed **org.gtk.Gtk3theme.Adapta-Nokto** from flathub + some apps.
But for example Gnome Twitch and Corebird do use the default theme, not Adapta-Nokto, which I set as system theme.

My system:
Manjaro Linux (based on Arch)
Kernel 4.14-rc7
Desktop: KDE-Plasma 5.11.2
flatpak  0.10.0-1

System GTK theme settings:
![image](https://user-images.githubusercontent.com/12885163/32416217-4a164bbc-c246-11e7-9b08-c55fb767d460.png)

Installed flatpaks:
![image](https://forum.manjaro.org/uploads/default/original/3X/f/b/fbb6e996a73eecfa37425738b526a1d7b35631cb.png)

**Comment by TingPing** [comment]
I'd guess it has to do with how the KDE settings set the Gtk theme. If it sets it by writing to `~/.config/gtk-3.0/settings.ini` that won't do anything. It has to set it over XSettings.

**Comment by Bleuzen** [comment]
My `.config/gtk-3.0/settings.ini`:

```
[Settings]
gtk-application-prefer-dark-theme=false
gtk-button-images=0
gtk-cursor-theme-name=breeze_cursors
gtk-fallback-icon-theme=gnome
gtk-font-name=Noto Sans Regular 10
gtk-icon-theme-name=Papirus-Adapta-Nokto
gtk-menu-images=0
gtk-primary-button-warps-slider=0
gtk-theme-name=Adapta-Nokto
gtk-toolbar-style=GTK_TOOLBAR_ICONS
```

Here the theme is Adapta-Nokto, which is what I want. So I guess KDE only sets it here.

**Comment by TingPing** [comment]
Yes sadly that is useless for sandboxed applications. You'll surely need to discuss this with the KDE folks.

**Comment by Bleuzen** [comment]
KDE bug:
https://bugs.kde.org/show_bug.cgi?id=387091

**Comment by TingPing** [comment]
@Bleuzen Thanks for that, Sadly XSettings isn't exactly trivial to use but some more information that can be added to that issue:

- https://standards.freedesktop.org/xsettings-spec/xsettings-0.5.html
- https://github.com/stefwalter/xdg-specs/tree/master/xsettings
- https://github.com/GNOME/gnome-settings-daemon/tree/master/plugins/xsettings

The specific XSetting is `Net/ThemeName` but there are others for cursor and icon theme.

**Comment by lmintmate** [comment]
I don't think the issue is KDE only, given that I have the exact same problem on my computer, which has Linux Mint MATE 1.18 (which has transitioned to Gtk3) as a DE. I installed Arc as a theme, and it didn't apply, as in e.g. LibreOffice it still used Adwaita, and then tried Greybird and still the same (and LibreOffice in its Flatpak page says it uses 3.24). In my case the system theme I use is not the same as the Flatpak theme installed, as I use Zukitwo otherwise (I used to use Arc but since going to MATE 1.18 via the update from Mint 18.1 to 18.2 it messes my toolbar). Here's some system info:
My system:
Linux Mint 18.3
Flatpak 0.10.0
Desktop: MATE 1.18 (Gtk3)
Kernel 4.4.0-109-generic
Currently installed flatpak packages:
```
flatpak list                                      
Ref                                            Options               
com.github.robertsanseries.ciano/x86_64/stable system,current        
com.skype.Client/x86_64/stable                 system,current        
org.audacityteam.Audacity/x86_64/stable        system,current        
org.gnome.clocks/x86_64/stable                 system,current        
org.gnome.gitg/x86_64/stable                   system,current        
org.libreoffice.LibreOffice/x86_64/stable      system,current        
io.elementary.code.Locale/x86_64/stable        system,runtime,partial
org.freedesktop.Platform.ffmpeg/x86_64/1.6     system,runtime        
org.freedesktop.Platform/x86_64/1.6            system,runtime        
org.freedesktop.Sdk/x86_64/1.6                 system,runtime        
org.gnome.Platform/x86_64/3.24                 system,runtime        
org.gnome.Platform/x86_64/3.26                 system,runtime        
org.gnome.gedit.Locale/x86_64/stable           system,runtime,partial
org.gtk.Gtk3theme.Greybird/x86_64/3.22         system,runtime
```
Surprisingly, I don't seem to have the .config/gtk-3.0/settings.ini file (only a bookmarks file is in there).
Given that, I have to admit I'm not sure if the cause is the same as with the other person that has the problem, but certainly the symptoms are the same. Thanks in advance for understanding.

**Comment by TingPing** [comment]
This was fixed by `kde-gtk-config` 5.11.95 https://github.com/KDE/kde-gtk-config/commit/87040960da7e9e587b4cb61251807e164aa53483

@lmintmate Your issue is probably unrelated.

**Comment by lmintmate** [comment]
I'll open a separate issue for my own problem then.

**Comment by TingPing** [comment]
@Bleuzen Which apps and which theme?

**Comment by Bleuzen** [comment]
@TingPing Adapta-Nokto theme
and apps I tryed are: Gnome-Twitch, Corebird, Peek

**Comment by TingPing** [comment]
@Bleuzen You can just manually `flatpak install flathub org.gtk.Gtk3theme.Adapta-Nokto` for now.

**Comment by Bleuzen** [comment]
@TingPing I already have it installed:
```
$ flatpak list
Ref                                                  Options       
com.discordapp.Discord/x86_64/stable                 system,current
com.play0ad.zeroad/x86_64/stable                     system,current
com.realm667.WolfenDoom_Blade_of_Agony/x86_64/stable system,current
com.spotify.Client/x86_64/stable                     system,current
com.uploadedlobster.peek/x86_64/stable               system,current
com.vinszent.GnomeTwitch/x86_64/stable               system,current
com.visualstudio.code/x86_64/stable                  system,current
io.atom.Atom/x86_64/stable                           system,current
io.github.gillesdegottex.FMIT/x86_64/stable          system,current
org.baedert.corebird/x86_64/stable                   system,current
org.shotcut.Shotcut/x86_64/stable                    system,current
org.freedesktop.Platform.GL.nvidia-396-24/x86_64/1.4 system,runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6      system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6           system,runtime
org.freedesktop.Platform/x86_64/1.6                  system,runtime
org.freedesktop.Sdk/x86_64/1.6                       system,runtime
org.gnome.Platform/x86_64/3.26                       system,runtime
org.gtk.Gtk3theme.Adapta-Nokto/x86_64/3.22           system,runtime
org.gtk.Gtk3theme.Adapta/x86_64/3.22                 system,runtime
org.kde.KStyle.Adwaita/x86_64/5.9                    system,runtime
org.kde.Platform/x86_64/5.9                          system,runtime
```

**Comment by TingPing** [comment]
Oh sorry you indeed are encountering the issue linked above: https://bugs.kde.org/show_bug.cgi?id=387091

**Comment by Bleuzen** [comment]
@TingPing Hm, I thought it was fixed by https://github.com/KDE/kde-gtk-config/commit/87040960da7e9e587b4cb61251807e164aa53483 :/

**Comment by TingPing** [comment]
Two different problems. On Xorg Gtk gets theme information over XSettings.

**Comment by pecigonzalo** [comment]
Does that apply to apps that use `"--filesystem=home",` ? shouldnt in that case the `.config/gtk-3.0/settings.ini` files be passed in? EG: Slack

**Comment by ZeroAurora** [comment]
It doesn't work for me too.
`~/.config/gtk-3.0/settings.ini`:
```
[Settings]
gtk-application-prefer-dark-theme=false
gtk-button-images=0
gtk-cursor-theme-name=Adwaita
gtk-fallback-icon-theme=Adwaita
gtk-font-name=Sans Serif  10
gtk-icon-theme-name=Papirus
gtk-menu-images=0
gtk-primary-button-warps-slider=0
gtk-theme-name=Materia
gtk-toolbar-style=GTK_TOOLBAR_ICONS
```
`$ flatpak list`:
```
Name                                               Application ID                                     Version             Branch            Installation
Beaker                                             com.beakerbrowser.Beaker                           0.8.8               stable            system
LMMS                                               io.lmms.LMMS                                       1.2.0               stable            system
Freedesktop Platform                               org.freedesktop.Platform                           18.08.34            18.08             system
Intel                                              org.freedesktop.Platform.VAAPI.Intel                                   18.08             system
html5-codecs                                       org.freedesktop.Platform.html5-codecs                                  18.08             system
Freedesktop SDK                                    org.freedesktop.Sdk                                18.08.34            18.08             system
Fractal                                            org.gnome.Fractal                                  4.0.0               stable            system
GNOME Application Platform version 3.32            org.gnome.Platform                                                     3.32              system
Materia GTK+ theme                                 org.gtk.Gtk3theme.Materia                                              3.22              system
Materia-compact GTK+ theme                         org.gtk.Gtk3theme.Materia-compact                                      3.22              system
Materia-dark GTK+ theme                            org.gtk.Gtk3theme.Materia-dark                                         3.22              system
Materia-dark-compact GTK+ theme                    org.gtk.Gtk3theme.Materia-dark-compact                                 3.22              system
Materia-light GTK+ theme                           org.gtk.Gtk3theme.Materia-light                                        3.22              system
Materia-light-compact GTK+ theme                   org.gtk.Gtk3theme.Materia-light-compact                                3.22              system
KDE Application Platform                           org.kde.Platform                                                       5.12              system
```
And https://bugs.kde.org/show_bug.cgi?id=387091 is still not fixed :(

**Comment by refi64** [comment]
`~/.config/gtk-3.0/settings.ini` isn't read in Flatpaks afaik, try setting the theme using gsettings instead.

**Comment by ZeroAurora** [comment]
It was set in gsettings.
`gsettings list-recursively`:
```
<...>
org.gnome.desktop.interface icon-theme 'Papirus'
<...>
org.gnome.desktop.interface gtk-theme 'Materia'
<...>
```

**Comment by magicmyth** [comment]
As many people seem to be unaware of this there is a relatively simple workaround I've been using that others might find useful.

@ZeroAurora As mentioned it won't work without a daemon implementing the xsettings service spec. KDE does not do this but you can run other xsetting services like gnome-settings-daemon (a simple but bit of a hefty hammer approach) or using a lighter implementation like [xsettingsd](https://github.com/derat/xsettingsd).

So this is what you need to do. Install xsettingsd (seems to be in most distro's repos), and create the file: `~/.xsettingsd` with the following content:
```
Net/ThemeName "Materia"
Net/IconThemeName "Papirus"
```
Substitute _Materia_ for whatever the name of the theme you are using is called (e.g "Breeze"). Now as a test run in the terminal execute: `xsettingsd`. If you don't see an error the daemon has bailed out then check your flatpak gtk app and you should see the expected theme applied. If all is good then go to Plasma's System Settings and go to _Autostart_ (under Workspace > Startup and Shutdown) and click "Add Program" and enter _xsettingsd_ and click OK. Now when you next log into your Plasma session the correct theme should be applied. Note that changing the theme in Plasma's system settings will not update your xsettingsd config so don't forget to edit the file and also don't forget to run `flatpak update` so the theme is downloaded and applied.

Ultimately people need to be making a feature request at [KDE's issue tracker](https://bugs.kde.org) for them to implement the freedesktop xsettings protocol.

**Comment by benburrill** [comment]
Another workaround (for those who are OK being a bit flexible with the sandbox) that I haven't seen mentioned explicitly anywhere is to allow access to the gtk-3.0 configuration.  This can be applied to all apps with the command:

```sh
flatpak override --user --filesystem=xdg-config/gtk-3.0
```

Note that attempting to allow access to `~/.config/gtk-3.0` does not work.  This is because the flatpak apps do not check there at all, but they do check `~/.var/app/<APP>/config/gtk-3.0/settings.ini` files, and using `xdg-config` mounts it there.

Of course you can also do `sudo flatpak override --system ...` to do it system-wide, or specify a particular app to use rather than applying the setting globally.

**Comment by Hippo0o** [comment]
@benburrill thanks a lot!
With
```
flatpak override --user --filesystem=~/.themes:ro
flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
```
i can finally set my custom theme selected with lxappearance under i3.

**Comment by oxwivi** [comment]
> Another workaround (for those who are OK being a bit flexible with the sandbox) that I haven't seen mentioned explicitly anywhere is to allow access to the gtk-3.0 configuration. This can be applied to all apps with the command:
> 
> ```shell
> flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
> ```
> 
> Note that attempting to allow access to `~/.config/gtk-3.0` does not work. This is because the flatpak apps do not check there at all, but they do check `~/.var/app/<APP>/config/gtk-3.0/settings.ini` files, and using `xdg-config` mounts it there.
> 
> Of course you can also do `sudo flatpak override --system ...` to do it system-wide, or specify a particular app to use rather than applying the setting globally.

I'm trying to fix Flatpak GTK apps not picking up any settings defined by KDE, including fonts, cursors and themes. I think these `xdg-config` series might provide the solution. Could you tell me how I can figure out what sort of settings there are besides `gtk-3.0`?

**Comment by benburrill** [comment]
@oxwivi Oops forgot to respond.  The XDG config directory is normally `~/.config`, so basically if there are things in `~/.config` that you want the flatpak app to see, you would override use `flatpak override --user --filesystem=xdg-config/whatever:ro`.
 
I initially figured out that flatpak was checking in `~/.var/app/<APP>/config/gtk-3.0/` using strace, e.g. `strace -ff -e trace=file flatpak run <APP> 2>&1`.  That might be helpful as a last resort if you can't figure out why it isn't reading the config.

**Comment by oxwivi** [comment]
Sorry for the late response, but `xdg-config:ro` does not translate to complete `.config/` access. I tried it before, I tried it again today, both times without `xdg-config/gtk-3.0:ro` override, and neither times did Firefox picked up the `gtk-3.0` settings.

**Comment by benburrill** [comment]
@oxwivi You're right.  I didn't test it beforehand, I was just basing it on the man page, which explicitly mentions using the xdg- prefixed dirs by themselves without a path.  Not really sure why it doesn't work, I'm probably missing something about what the flatpak overrides actually do.
