### ISSUE TITLE
TLS support is not available

### ISSUE THREAD

**Issue by kplesko** [flatpak/flatpak#1207]
Hi! 

I've tried to install Gnome builder via flatpak but failed. I've followed instructions but every time I get the same error message.

Input:
flatpak install --from https://flathub.org/repo/appstream/org.gnome.Builder.flatpakref

Error message:
error: Can't load uri https://flathub.org/repo/appstream/org.gnome.Builder.flatpakref: TLS support is not available

I've searched through web far and wide but haven't found this issue and its solution. What is the problem?

Other information:
Ubuntu 16.04.1
Flatpak version 0.10.1

**Comment by mwleeds** [comment]
You should post what OS you're on and what version of flatpak you're using

**Comment by alexlarsson** [comment]
Do you have glib-networking installed?

**Comment by kplesko** [comment]
Yes! I checked, it's installed.

**Comment by alexlarsson** [comment]
The problem is that your libsoup for some reason doesn't seem to have SSL support, but glib-networking should add that...

**Comment by kplesko** [comment]
Well, it's still not working. The version of libsoup is 2.52.2-1ubuntu0.2. Am I really the only one who has this problem? Will reinstalling help? And what should I reinstall: flatpak or some library?

**Comment by madurapa** [comment]
It could be your network, firewall, try different network or restart your network

**Comment by MVinhas** [comment]
I've also issues with this, when I try to install any Flatpak app, I get this error: 

error: Unable to load summary from remote flathub: [35] SSL connect error

Currently running Fedora 28, `glib-networking` already installed

**Comment by kplesko** [comment]
What did you do to fix it?

**Comment by bam80** [comment]
Having the same issue with this flatpak: https://phabricator.kde.org/source/flatpak-kde-applications/browse/master/org.kde.discover.json
After install, I run in it's CLI:
```
$ flatpak run --command=sh org.kde.discover   
~$ flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
Can't load uri https://flathub.org/repo/flathub.flatpakrepo: TLS support is not available

**Comment by julk3772** [comment]
I've also issues with this, when I try to install any Flatpak app, I get this error:

error: Unable to load summary from remote flathub: [35] SSL connect error  in Deepin

**Comment by pavlosun** [comment]
Same thing here on debian 10. Flatpak 1.4.3
```
$ dpkg -l | grep glib-netw
ii  glib-networking:amd64                     2.62.1-1                              amd64        network-related giomodules for GLib
ii  glib-networking-common                    2.62.1-1                              all          network-related giomodules for GLib - data files
ii  glib-networking-services                  2.62.1-1                              amd64        network-related giomodules for GLib - D-Bus services
```

libostree-1-1:amd64                       2019.5-1
```
$ flatpak --ostree-verbose update 
Looking for updates…
F: _ostree_fetcher_should_retry_request: error: 474:0 TLS support is not available, n_retries_remaining: 5
F: _ostree_fetcher_should_retry_request: error: 474:0 TLS support is not available, n_retries_remaining: 5
F: Error updating remote metadata for 'flathub': TLS support is not available
```
Please guid me to nail the potential source of the problem. Thanks.

**Comment by fpaquet** [comment]
Looks like some library version issue. Maybe not all features were compiled in.
I had some self compiled libraries in the LD_LIBRARY_PATH:

[moko:/home/fredy] flatpak remote-ls
error: TLS support is not available

[moko:/home/fredy] unsetenv LD_LIBRARY_PATH

[moko:/home/fredy] flatpak remote-ls
Ref                                                         Origin            
app.rednotebook.RedNotebook                                 flathub           
ar.com.tuxguitar.TuxGuitar                                  flathub           
at.priv.toastfreeware.ConfClerk                             flathub           
...

**Comment by niansa** [comment]
same problem here and my connection definitely isn't censored.
also unsetting LD_LIBRARY_PATH didn't help
i'm on Kubuntu 20.04 (Upgraded from 19.04)

**Comment by FireShredder24** [comment]
Same problem here, on Debian Buster stable.  Flatpak version 1.10.1-1~bpo10+1.
When I try to add FlatHub with 
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`,
I get 
`error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: TLS support is not available`

**Comment by lnx-soul** [comment]
I had to run the `remote-add` command with `sudo` and also any installation commands as well.  Definitely not ideal, since even adding the `--user=name` flag still installs applications as root.

**Comment by bootcry** [comment]
having same issue on ubuntu 21.04 fresh install.
```$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: TLS support is not available
```
already checked gnutls and glib-networking
libgnutls30 -> 3.7.1-3ubuntu1
glib-networking -> 2.66.0-2

**Comment by serpro69** [comment]
Have same issue.
```
5.8.0-63-generic #71~20.04.1-Ubuntu

✓ ~→ flatpak --version
Flatpak 1.11.2


✓ ~→ dpkg -l | grep glib-netw
ii  glib-networking:amd64                      2.64.2-1ubuntu0.1                         amd64        network-related giomodules for GLib
ii  glib-networking-common                     2.64.2-1ubuntu0.1                         all          network-related giomodules for GLib - data files
ii  glib-networking-services                   2.64.2-1ubuntu0.1                         amd64        network-related giomodules for GLib - D-Bus services
```

Anyone has any solutions apart from trying to change the network? (that didn't help me)

**Comment by shadiakiki1986** [comment]
My workaround was to download the repo file from the URL with curl and then use the `--from` option to add the remote from the downloaded file.

```
# flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
# error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: TLS support is not available
# same error with sudo as well

curl -o flathub.flatpakrepo https://flathub.org/repo/flathub.flatpakrepo
sudo flatpak remote-add --if-not-exists flathub --from flathub.flatpakrepo
# without sudo, I get: error: Flatpak system operation ConfigureRemote not allowed for user
```

**Comment by squili** [comment]
it's a bit dirty and hacky, but the workaround i've found to work is building and installing glib-networking from source after installing it from the package manager

**Comment by musoke** [comment]
I was having the same issue.  @amerixan's solution of running everything through sudo works.

Ubuntu 20.04
flatpak 1.6

**Comment by haggen88** [comment]
[try](https://discourse.flathub.org/t/unacceptable-tls-certificate-ubuntu-20-04-a-solution/716)  sudo apt install --reinstall ca-certificates

**Comment by dfontenot** [comment]
Still running into the same error as others have reported on Ubuntu 20.04 after reinstalling ca-certs

**Comment by serpro69** [comment]
Reinstalling `ca-certificates` does not help me either:
```
✗[1] ~/Projects/personal/personal/kotlin-faker→ sudo apt install --reinstall ca-certificates
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-5.11.0-37-generic linux-hwe-5.11-headers-5.11.0-37 linux-image-5.11.0-37-generic linux-modules-5.11.0-37-generic linux-modules-extra-5.11.0-37-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 1 not upgraded.
Need to get 145 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://no.archive.ubuntu.com/ubuntu focal-updates/main amd64 ca-certificates all 20210119~20.04.2 [145 kB]
Fetched 145 kB in 0s (1,853 kB/s)
Preconfiguring packages ...
(Reading database ... 390446 files and directories currently installed.)
Preparing to unpack .../ca-certificates_20210119~20.04.2_all.deb ...
Unpacking ca-certificates (20210119~20.04.2) over (20210119~20.04.2) ...
Setting up ca-certificates (20210119~20.04.2) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for ca-certificates (20210119~20.04.2) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
✓ ~/Projects/personal/personal/kotlin-faker→ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo -v
F: Opening system flatpak installation at path /var/lib/flatpak
F: Loading https://flathub.org/repo/flathub.flatpakrepo using libsoup
error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: TLS support is not available

✗[1] ~/Projects/personal/personal/kotlin-faker→
```

**Comment by dfontenot** [comment]
Was not able to resolve the TLS error after reinstalling `glib-networking` either. Also tried removing flatpak from Ubuntu and re-installing, but the same issue occurred.

**Comment by cata0309** [comment]
I experience the same error and the above solutions did not help.

**Comment by ahmetbombaci** [comment]
In my case,  I was using Alacritty terminal from snap. It is not supported officially. I switched back to GNOME Terminal and the issue is resolved.

**Comment by tanguy-launay** [comment]
After looking at https://github.com/flatpak/flatpak/issues/1207#issuecomment-1034942201 answer I find out that it may be because the gio module dir is not correctly defined.
I tried
export GIO_MODULE_DIR=/usr/lib/x86_64-linux-gnu/gio/modules/
and then flatpak worked

**Comment by smcv** [comment]
@tanguy-launay:
> I tried `export GIO_MODULE_DIR=/usr/lib/x86_64-linux-gnu/gio/modules` and then flatpak worked

You haven't said what OS you are using or where you got your GLib library, but it sounds as though you have the `glib-networking` package from Debian or Ubuntu, combined with GLib libraries from somewhere else (locally compiled or from a different distribution). This is not a Flatpak bug. Flatpak requires GLib libraries and `glib-networking` modules that are compatible with each other; if you don't have those, please fix your installation before using Flatpak.

**Comment by estatistics** [comment]
Updating / reinstalling glib network, glib utls, ca certificates not solved the problem (try installing JASP flatpak)

`curl -o flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`
`sudo flatpak remote-add --if-not-exists flathub --from flathub.flatpakrepo`

and WITHOUT SUDO (otherwise TLS error is thrown)

`flatpak install flathub-beta org.jaspstats.JASP`
and voila.... it is downloading / installing.....

**Comment by JhonnyRice** [comment]
@estatistics same issue and just removing sudo solved the issue.. wtf???

**Comment by Synetech** [comment]
They changed the subdomain without updating the instructions. Just prepend **"dl."** to the URL:

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

**Comment by Pira4Ever** [comment]
> After looking at [#1207 (comment)](https://github.com/flatpak/flatpak/issues/1207#issuecomment-1034942201) answer I find out that it may be because the gio module dir is not correctly defined. I tried export GIO_MODULE_DIR=/usr/lib/x86_64-linux-gnu/gio/modules/ and then flatpak worked

I'm usin Zorin OS 16.2 and for some reason I could not install any flatpak.
After running export GIO_MODULE_DIR=/usr/lib/x86_64-linux-gnu/gio/modules/ the flatpak started working again.

**Comment by oryband** [comment]
> I was using Alacritty terminal from snap.

@ahmetbombaci i can confirm that for some benign reason, Alacritty installed via Ubuntu Snap fails on `gio cat https:// ...` commands, which also flatpak.

**Comment by smcv** [comment]
> Alacritty installed via Ubuntu Snap fails
> In my case, I was using Alacritty terminal from snap

I've seen this before, in a Steam issue report.

> maybe related to this issue? https://github.com/snapcrafters/alacritty/pull/2

Yes, it is. The Snap-packaged version of Alacritty is running programs (Steam, Flatpak, your shell, everything else) in an environment that is not what they expect, and therefore some of those programs will fail to work. This is a bug in the Snap-packaged version of Alacritty, and is not a bug in Flatpak or Steam or whatever other program is not working when its expectations are not met.

Sorry, the Snap-packaged version of Alacritty doesn't seem to be fit-for-purpose. The whole point of a terminal emulator is to run random programs that are not controlled by the author/packager of the terminal emulator, with no special sandboxing applied to those programs (beyond whatever sandboxing they might already have from having been installed via Flatpak or Snap or similar). If it can't do that correctly, then it isn't doing its job.

Similar factors are the reason why terminal emulators that are available via Flatpak (like [Konsole](https://flathub.org/apps/org.kde.konsole)) have to be flagged as "Potentially unsafe: arbitrary permissions": if they didn't have that sandbox escape allowed, then they would be useless.

I would recommend installing a trusted terminal emulator from your operating system's package repository (apt/dpkg, yum/zypp/RPM, or whatever else your operating system uses), and using that to run whatever command-line programs you want to run.

**Comment by sklarame** [comment]
I got the same error today on Ubuntu 20.04, and the problem was solved after reinstalling ca-certificates and glib-networking by apt:

sudo apt install --reinstall ca-certificates glib-networking

Hope this helps anyone who get the same error.

**Comment by nickaigi** [comment]
Using the comment from @smcv , I uninstalled the snap version of `alacritty` and installed alacritty by building it  from source.
This solved the `TLS support not available` problem on my system: Ubuntu 22.04.

**Comment by smcv** [comment]
Several years after the original report, we will probably never know what the root cause was for the issue originally seen by @kplesko, so I'm going to close this as "not our bug".

One common reason for "TLS support not available" seems to be that the Snap version of alacritty either isn't fit-for-purpose, or wasn't at some point in the past: the entire point of a terminal emulator is to be able to run arbitrary programs, but the Snap version of alacritty can't do that. (e.g. https://github.com/flatpak/flatpak/issues/1207#issuecomment-2049440102, https://github.com/flatpak/flatpak/issues/1207#issuecomment-1790282539, https://github.com/flatpak/flatpak/issues/1207#issuecomment-1072778995, https://github.com/snapcrafters/alacritty/pull/2)

Another possible reason for "TLS support not available" is that glib-networking is missing, broken or incorrectly installed.

Another possible reason for "TLS support not available" is that ca-certificates (or whatever is the name of the equivalent package in your distribution) is missing, broken or incorrectly installed.

Another possible reason for "TLS support not available" is that you have a locally-installed version of some library used by Flatpak, perhaps in `/usr/local`, and it is outdated, misconfigured, incompatible or broken. GLib, glib-networking, libsoup, libcurl are examples of libraries that might have this effect if not installed correctly.

None of these are really a bug in Flatpak, so there is no change in Flatpak that could solve them. https://github.com/flatpak/flatpak/issues/1207#issuecomment-1034942201 provides some starting points for figuring out what might be going wrong on your system.

If `gio cat` works in a particular situation, but Flatpak doesn't, then *that* might be a Flatpak issue: if so, please open a separate issue with full details.

The Flatpak maintainers have limited time available and are not able to provide personal technical support, especially for dealing with bugs or mis-installation in non-Flatpak packages that Flatpak depends on. Please help us to use our time efficiently by minimizing the noise added to Flatpak issue reports for non-Flatpak bugs.

**Comment by DairyFreeHem** [comment]
> After looking at [#1207 (comment)](https://github.com/flatpak/flatpak/issues/1207#issuecomment-1034942201) answer I find out that it may be because the gio module dir is not correctly defined. I tried export GIO_MODULE_DIR=/usr/lib/x86_64-linux-gnu/gio/modules/ and then flatpak worked

Worked for me on POP-OS 22.04 LTS
