### ISSUE TITLE
"flatpak uninstall --unused" removes runtimes that are later reinstalled by "flatpak update"

### ISSUE THREAD

**Issue by LaurentBonnaud** [flatpak/flatpak#1766]
## Linux distribution and version
Ubuntu 18.04
## Flatpak version
Flatpak 0.11.8.1 from alexlarsson PPA
## Description of the problem
`flatpak uninstall --unused` removes runtimes that are later reinstalled by `flatpak update`
## Steps to reproduce
```
# flatpak uninstall --unused
Uninstalling from system:
 runtime/org.freedesktop.Platform.GL.default/x86_64/1.6
Is this ok? [y/n]: y
Uninstalling: org.freedesktop.Platform.GL.default/x86_64/1.6
```
And later:
```
# flatpak update
Looking for updates...
Installing: org.freedesktop.Platform.GL.default/x86_64/1.6 from gnome
[####################] 1 delta parts, 7 loose fetched; 47832 KiB transferred in 10 seconds
Now at fefd42de91fd.
```

**Comment by LaurentBonnaud** [comment]
On another system I see:
```
# flatpak uninstall --unused
Uninstalling from system:
 runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6
Is this ok? [y/n]: y
Uninstalling: org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6
```
and then:
```
# flatpak update
Looking for updates...
Installing: org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 from flathub
[####################] 1 delta parts, 2 loose fetched; 2621 KiB transferred in 0 seconds
Now at 818a1504fad1.
```

**Comment by alexlarsson** [comment]
The downloading of these extensions are toggled based on the current GL driver and if an intel GPU is detected. I wonder if the detection returns different results in the two runs somehow.

**Comment by LaurentBonnaud** [comment]
> The downloading of these extensions are toggled based on the current GL driver and if an intel GPU is detected.

All my systems do have an Intel GPU.

> I wonder if the detection returns different results in the two runs somehow.

Is it possible to test this hypothesis?

**Comment by alexlarsson** [comment]
I note the '#' in your samples. Are you running these commands as root?

**Comment by alexlarsson** [comment]
So, there are two things here. First the download. It *should* download a particular gl driver if the name is listed in `flatpak --gl-drivers`, and `default` *should* be listed. It should download VAAPI.Intel if you have a `/sys/module/i915` file. So, the download part seems correct.

The problem seems to be on the uninstall side. It should find that the runtime is used, and then that the extension is used, and since these are marked they should not be uninstalled. But for whatever reason that doesn't seem to be happening.  The weird thing is that we're not currently doing any intel/gl checks when detecting what is used. As long as its installed it should be marked used...

**Comment by LaurentBonnaud** [comment]
> I note the '#' in your samples. Are you running these commands as root?

I do.

**Comment by LaurentBonnaud** [comment]
> It should download a particular gl driver if the name is listed in flatpak --gl-drivers, and default should be listed. 

"default" is listed:

```
# flatpak --gl-drivers
default
host
```

**Comment by alexlarsson** [comment]
Unrelated to this issue, but you should be able to rely on the policykit helper and never run flatpak commands as root, thus going the downloads etc non-privileged, for increased security.

**Comment by LaurentBonnaud** [comment]
> It should download VAAPI.Intel if you have a /sys/module/i915 file. 

On my system /sys/module/i915 is a directory:
```
# ls -ld /sys/module/i915/
drwxr-xr-x 7 root root 0 Jun 11 11:37 /sys/module/i915/
```

**Comment by LaurentBonnaud** [comment]
Thank you for the fix!

**Comment by LaurentBonnaud** [comment]
I installed flatpak 0.11.8.2-flatpak1~bionic on my 2 Ubuntu 18.04 systems:
 - the problem is fixed on one of them
 - on the second one, I still get the uninstall / install flip-flop:
```
$ flatpak uninstall --unused
Uninstalling from system:
 runtime/org.freedesktop.Platform.GL.default/x86_64/1.6
Is this ok? [y/n]: y
Uninstalling: org.freedesktop.Platform.GL.default/x86_64/1.6

$ flatpak uninstall --unused
Nothing unused to uninstall

$ flatpak update
Looking for updates...
Installing: org.freedesktop.Platform.GL.default/x86_64/1.6 from gnome
[####################] 1 delta parts, 7 loose fetched; 47832 KiB transferred in 9 seconds
Now at fefd42de91fd.

$ flatpak uninstall --unused
Uninstalling from system:
 runtime/org.freedesktop.Platform.GL.default/x86_64/1.6
Is this ok? [y/n]: n
```

**Comment by LaurentBonnaud** [comment]
For the record, the uninstall issue is caused by the gnome runtimes from the "gnome" remote.  After uninstalling them and replacing them by the same runtimes but from the "flathub" remote, the problem is fixed.

**Comment by goncalossilva** [comment]
I've been facing the same problem for a couple of months now. Currently running Flatpak 1.4.2 on Fedora 30. Only a single Nvidia GPU, no integrated GPU.

```
$ flatpak --gl-drivers
nvidia-430-40
default
host
```

And the loop itself:

```
$ flatpak update
Looking for updates…
Required runtime for org.freedesktop.Platform.GL32.nvidia-430-40/x86_64/1.4 (runtime/org.freedesktop.Platform/i386/1.6) found in remote flathub
Do you want to install it? [Y/n]: 
Required runtime for org.freedesktop.Platform.GL.nvidia-430-40/x86_64/1.4 (runtime/org.freedesktop.Platform/x86_64/1.6) found in remote flathub
Do you want to install it? [Y/n]: 


        ID                                          Arch     Branch   Remote   Download
 1. [✓] org.freedesktop.Platform                    i386     1.6      flathub  170.0 MB / 429.7 MB
 2. [✓] org.freedesktop.Platform.GL.nvidia-430-40   i386     1.4      flathub  111.3 MB / 111.7 MB
 3. [✓] org.freedesktop.Platform.ffmpeg             i386     1.6      flathub    3.0 MB / 3.0 MB
 4. [✓] org.freedesktop.Platform.Locale             i386     1.6      flathub   14.3 kB / 177.1 MB
 5. [✓] org.freedesktop.Platform                    x86_64   1.6      flathub  163.3 kB / 395.4 MB
 6. [✓] org.freedesktop.Platform.Locale             x86_64   1.6      flathub    1.0 kB / 177.1 MB

Installation complete.
$ flatpak remove --unused


        ID                                                   Arch             Branch
 1. [-] org.freedesktop.Platform.GL.nvidia-430-40            i386             1.4
 2. [-] org.freedesktop.Platform                             i386             1.6
 3. [-] org.freedesktop.Platform.Locale                      i386             1.6
 4. [-] org.freedesktop.Platform.ffmpeg                      i386             1.6
 5. [-] org.freedesktop.Platform                             x86_64           1.6
 6. [-] org.freedesktop.Platform.Locale                      x86_64           1.6

Uninstall complete.
$ flatpak update
Looking for updates…
Required runtime for org.freedesktop.Platform.GL32.nvidia-430-40/x86_64/1.4 (runtime/org.freedesktop.Platform/i386/1.6) found in remote flathub
Do you want to install it? [Y/n]: 
Required runtime for org.freedesktop.Platform.GL.nvidia-430-40/x86_64/1.4 (runtime/org.freedesktop.Platform/x86_64/1.6) found in remote flathub
Do you want to install it? [Y/n]: 


        ID                                          Arch     Branch   Remote   Download
 1. [✓] org.freedesktop.Platform                    i386     1.6      flathub  170.0 MB / 429.7 MB
 2. [✓] org.freedesktop.Platform.GL.nvidia-430-40   i386     1.4      flathub  111.3 MB / 111.7 MB
 3. [✓] org.freedesktop.Platform.ffmpeg             i386     1.6      flathub    3.0 MB / 3.0 MB
 4. [✓] org.freedesktop.Platform.Locale             i386     1.6      flathub   14.3 kB / 177.1 MB
 5. [✓] org.freedesktop.Platform                    x86_64   1.6      flathub  163.3 kB / 395.4 MB
 6. [✓] org.freedesktop.Platform.Locale             x86_64   1.6      flathub    1.0 kB / 177.1 MB

Installation complete.
```

And so on. Everything is installed from Flathub.

**Comment by BjoernDaase** [comment]
Fedora 31 has the same problem.

**Comment by Cervoxx** [comment]
Encountering this issue as well. Running Pop!_OS 19.04 and using the flatpak PPA. I'd be happy to provide any assistance needed to resolve the issue.

```cervox@pop-os-laptop:~$ flatpak --version
Flatpak 1.4.3
cervox@pop-os-laptop:~$ flatpak uninstall --unused


        ID                                          Arch          Branch
 1. [-] org.freedesktop.Platform.VAAPI.Intel        x86_64        1.6
 2. [-] org.freedesktop.Platform.ffmpeg             x86_64        1.6
 3. [-] org.freedesktop.Platform                    x86_64        1.6
 4. [-] org.freedesktop.Platform.Locale             x86_64        1.6

Uninstall complete.
cervox@pop-os-laptop:~$ flatpak update
Looking for updates…
Required runtime for org.freedesktop.Platform.GL.nvidia-435-21/x86_64/1.4 (runtime/org.freedesktop.Platform/x86_64/1.6) found in remote flathub
Do you want to install it? [Y/n]: 


        ID                                   Arch   Branch Remote  Download
 1. [✓] org.freedesktop.Platform             x86_64 1.6    flathub 184.6 MB / 395.4 MB
 2. [✓] org.freedesktop.Platform.VAAPI.Intel x86_64 1.6    flathub   2.7 MB / 2.7 MB
 3. [✓] org.freedesktop.Platform.ffmpeg      x86_64 1.6    flathub   2.9 MB / 2.9 MB
 4. [✓] org.freedesktop.Platform.Locale      x86_64 1.6    flathub  14.3 kB / 177.1 MB

Installation complete.
cervox@pop-os-laptop:~$ flatpak list
Name                                                  Application ID                                          Version             Branch     Installation
OBS Studio                                            com.obsproject.Studio                                   23.2.1-modified     stable     system
Blender                                               org.blender.Blender                                     2.80                stable     system
Freedesktop.org Application Platform version 1.6      org.freedesktop.Platform                                1.6                 1.6        system
Freedesktop Platform                                  org.freedesktop.Platform                                19.08.1             19.08      system
default                                               org.freedesktop.Platform.GL.default                                         19.08      system
nvidia-435-21                                         org.freedesktop.Platform.GL.nvidia-435-21                                   1.4        system
Intel VAAPI Driver                                    org.freedesktop.Platform.VAAPI.Intel                                        1.6        system
Intel                                                 org.freedesktop.Platform.VAAPI.Intel                                        18.08      system
Intel                                                 org.freedesktop.Platform.VAAPI.Intel                                        19.08      system
FFmpeg extension                                      org.freedesktop.Platform.ffmpeg                                             1.6        system
html5-codecs                                          org.freedesktop.Platform.html5-codecs                                       18.08      system
openh264                                              org.freedesktop.Platform.openh264                                           19.08      system
Godot                                                 org.godotengine.Godot                                   3.1                 stable     system
Pop Gtk theme                                         org.gtk.Gtk3theme.Pop-slim-dark                                             3.22       system
KDE Application Platform                              org.kde.Platform                                                            5.12       system
QGnomePlatform                                        org.kde.PlatformTheme.QGnomePlatform                                        5.12       system
QGnomePlatform-decoration                             org.kde.WaylandDecoration.QGnomePlatform-decoration                         5.12       system
cervox@pop-os-laptop:~$ 
```

**Comment by Leeo97one** [comment]
This is still an issue. I'm using Arch Linux and Flatpak 1.5.0.
```
[leeo@leeo-arch-msi ~]$ flatpak update
Looking for updates…
Required runtime for org.freedesktop.Platform.GL.nvidia-435-21/x86_64/1.4 (runtime/org.freedesktop.Platform/x86_64/1.6) found in remote flathub
Do you want to install it? [Y/n]: 


        ID                                                 Branch               Remote               Download
 1. [✓] org.freedesktop.Platform                           1.6                  flathub              183,0 MB / 395,4 MB
 2. [✓] org.freedesktop.Platform.VAAPI.Intel               1.6                  flathub                2,7 MB / 2,7 MB
 3. [✓] org.freedesktop.Platform.ffmpeg                    1.6                  flathub                2,9 MB / 2,9 MB
 4. [✓] org.freedesktop.Platform.Locale                    1.6                  flathub              967,6 kB / 177,1 MB

Installation complete.
[leeo@leeo-arch-msi ~]$ flatpak uninstall --unused 


        ID                                                Branch
 1.     org.freedesktop.Platform.VAAPI.Intel              1.6
 2.     org.freedesktop.Platform.ffmpeg                   1.6
 3.     org.freedesktop.Platform                          1.6
 4.     org.freedesktop.Platform.Locale                   1.6

```

**Comment by robsonjorgefernandez** [comment]
Same on Ubuntu 19.10

<pre>
$ lsb_release -d
Description:	Ubuntu 19.10

$ flatpak --version
Flatpak 1.4.3

$ uname -r
5.3.0-19-generic
</pre>

<pre>
$ flatpak -y update ; flatpak -y uninstall --unused
Looking for updates…
Required runtime for org.freedesktop.Platform.GL.nvidia-435-21/x86_64/1.4 (runtime/org.freedesktop.Platform/x86_64/1.6) found in remote flathub


        ID                                         Arch             Branch           Remote            Download
 1. [✓] org.freedesktop.Platform                   x86_64           1.6              flathub             6,5 MB / 395,4 MB
 2. [✓] org.freedesktop.Platform.Locale            x86_64           1.6              flathub           143,5 kB / 177,1 MB

Installation complete.


        ID                                       Arch            Branch
 1. [-] org.freedesktop.Platform                 x86_64          1.6
 2. [-] org.freedesktop.Platform.Locale          x86_64          1.6

Uninstall complete.
</pre>

**Comment by TingPing** [comment]
All of the `1.6` issues are probably caused by #3173

**Comment by happydemic** [comment]
Ubuntu 18.04
```
$ flatpak update -y
Looking for updates…
Nothing to do.
$ flatpak uninstall --unused -y && flatpak update -y

        ID                                           Arch          Branch
 1. [-] org.freedesktop.Platform.VAAPI.Intel         x86_64        1.6
 2. [-] org.freedesktop.Platform.ffmpeg              x86_64        1.6
 3. [-] org.freedesktop.Platform                     x86_64        1.6
 4. [-] org.freedesktop.Platform.Locale              x86_64        1.6
 5. [-] org.freedesktop.Platform                     x86_64        19.08
 6. [-] org.freedesktop.Platform.Locale              x86_64        19.08
 7. [-] org.freedesktop.Sdk                          x86_64        1.6
 8. [-] org.freedesktop.Sdk.Locale                   x86_64        1.6
 9. [-] org.gnome.Sdk                                x86_64        3.26
10. [-] org.gnome.Sdk.Locale                         x86_64        3.26

        ID                                              Arch              Branch            Remote             Download
 1. [✓] org.freedesktop.Platform                        x86_64            1.6               flathub              184.3 MB / 395.4 MB
 2. [✓] org.freedesktop.Platform.Locale                 x86_64            1.6               flathub               14.3 kB / 177.1 MB
 3. [✓] org.freedesktop.Platform                        x86_64            19.08             flathub               11.1 MB / 237.7 MB
 4. [✓] org.freedesktop.Platform.Locale                 x86_64            19.08             flathub               16.8 kB / 318.9 MB
 5. [✓] org.freedesktop.Sdk                             x86_64            1.6               flathub              194.8 MB / 717.1 MB
 6. [✓] org.freedesktop.Sdk.Locale                      x86_64            1.6               flathub               14.3 kB / 177.1 MB
 7. [✓] org.gnome.Sdk                                   x86_64            3.26              flathub               95.7 MB / 809.5 MB
 8. [✓] org.freedesktop.Platform.VAAPI.Intel            x86_64            1.6               flathub                2.7 MB / 2.7 MB
 9. [✓] org.freedesktop.Platform.ffmpeg                 x86_64            1.6               flathub                2.9 MB / 2.9 MB
10. [✓] org.gnome.Sdk.Locale                            x86_64            3.26              flathub             14.4 kB / 187.2 MB

Installation complete.
```
Should this issue be reopened?

**Comment by LaurentBonnaud** [comment]
I do not see this bug any longer with flatpak 1.4.3.
Which flatpak version are you using?

**Comment by happydemic** [comment]
Also 1.4.3. 
Comment edited above.

**Comment by goncalossilva** [comment]
Same problem on 1.4.3 as well.

**Comment by LaurentBonnaud** [comment]
I don't seem to be able to reopen this bug, so you should probably open a new one.

**Comment by happydemic** [comment]
@TingPing [mentioned](https://github.com/flatpak/flatpak/issues/1766#issuecomment-545956131) this is likely due to https://github.com/flatpak/flatpak/issues/3173. 

So I'm not sure a new report is necessary?

**Comment by mzannoni** [comment]
Same issue here:
Fedora 31
Flatpak 1.4.3
NVIDIA discrete GPU

What's the status then? is there a new bug to check for updates?

**Comment by happydemic** [comment]
@mzannoni 
This bug - [reported with Flatpak 1.4.3](https://github.com/flatpak/flatpak/issues/1766#issuecomment-556963418) - seems to have been fixed in later releases. 

On Flatpak 1.6.0 I do not see it.

**Comment by mzannoni** [comment]
Thanks a lot!
I'll wait for the update to reach Fedora then.

**Comment by matilde-t** [comment]
I have the exact same bug, with Flatpak 1.12.7 and Pop!_OS 22.04 LTS

**Comment by jojo2357** [comment]
Sort of the same issue, but I can see a different 
"Autoremove":
```
 3. [-] org.freedesktop.Platform.openh264                                2.3.0                  r
 5. [-] org.freedesktop.Platform.openh264                                2.2.0                  r
```

Update:
```
 1. [✓] org.freedesktop.Platform.openh264            2.2.0            i            flathub           614.3 kB / 944.3 kB
```

On Pop 22.04 LTS and flatpak 1.12.7.

after installing the missing package, the remove does not remove any packages so for me it was a one-time thing
