### ISSUE TITLE
bwrap: Can't make symlink at /home/<username>/Pictures: File exists

### ISSUE THREAD

**Issue by PorcelainMouse** [flatpak/flatpak#2387]
## Linux distribution and version
Fedora 29
## Flatpak version
1.0.6
## Description of the problem
Cannot start steam, has worked in the past.

I've seen this before, and then it went away or I deleted the symlink and let steam recreate it or something. Why does this keep coming up?  Why does steam care about these directories that my Desktop Env manages?  This is non-standard behavior.  Steam is already using .local/share/flatpak/app/... .  Why does steam care about anything in $HOME?

Several other similar bugs exist, but the closest one is bug #1278, which is closed, yet he problem still exists.

## Steps to reproduce
$ flatpak run com.valvesoftware.Steam
bwrap: Can't make symlink at /home/pdestefa/Pictures: File exists

**Comment by ioogithub** [comment]
I have the same problem but with Music

$ flatpak run com.valvesoftware.Steam

bwrap: Can't make symlink at /home/oem/Music: File exists

**Comment by strootje** [comment]
I've had the same with my ~/Music folder.
My Music folder is a symlink which points to an external drive.
I have to rename my ~/Music folder, after which steam starts file. Once steam is started I can rename the Music folder back again.

I've read somewhere, and I'm sorry I cannot find the source anymore, that this is an issue with symlinks in ~ where ~ is persisted.

**Comment by RossComputerGuy** [comment]
I have the same problem on nixOS except it wants to symlink `~/.nix-profile`.

**Comment by Justinzobel** [comment]
Still an issue on 1.15.4

**Comment by hideki2k02** [comment]
I'm getting a similar problem but its because i made a script that runs at startup to generate a symlink at `/run/user/1000/discord-ipc-0`

`bwrap: Can't make symlink at /run/user/1000/discord-ipc-0: File exists`

One thing that is worth noting is that if its a hardlink Flatpak wont complain, so the current workarounds:
- Delete the Symlink that the program is complaining then run the program again
- Using a hardlink (In my case i've replaced my startup script to create a hardlink)

PS: Maybe a way to fix this is to just clear all symlinks once the program closes/Just ignore the symlink if it already exists for some reason.

**Comment by shvetsnikita** [comment]
> I have the same problem but with Music
> $ flatpak run com.valvesoftware.Steam
> bwrap: Can't make symlink at /home/oem/Music: File exists

Is there any way to workaround this by maybe changing something in Flatseal?

**Comment by shvetsnikita** [comment]
@rugk 

As I found out replacing symlinks with fstab binds works too, and x-gvfs-hide flag hide it from Nautilus.

**Comment by holocronweaver** [comment]
I see the issue is closed, but the problem seems to persist in flatpak `1.14.6`. Example for Heroic games with a symlinked desktop:

```
bwrap: Can't make symlink at /home/me/desktop: File exists
```

Looks like this will be coming to [1.15.7](https://github.com/flatpak/flatpak/releases/tag/1.15.7), but that is a preview release, not stable. Please release the fix in a stable version before closing the issue.

I found a different solution in the meantime...switched problematic packages to AppImage, no more issues with symlinks.

**Comment by chrisawi** [comment]
@holocronweaver

The issue was fixed in bubblewrap 0.9.0. I've personally tested several of the related issues (likely including this one) to confirm that.

Flatpak 1.15.7 is the first version to update its bundled copy, but most users would be getting bubblewrap separately packaged by their distro. As far as I can tell, bubblewrap doesn't use an even-odd versioning scheme, so that would be a suitable update candidate depending on your distro's update policy.

In any case, bug trackers don't keep issues open that have been fixed. If you can reproduce it with bubblewrap 0.9.0, we can re-evaluate.

**Comment by holocronweaver** [comment]
Thanks for the clarification. 

This raises more questions that answers though - why is a critical dependency of flatpak like bubblewrap left up to OS maintainers? Shouldn't it be bundled into flatpak so they are built and released together? (As you say, that's how the flatpak git repo works with bubblewrap as a git submodule, I assumed they were released as such as well, but I was mistaken.)

> bug trackers don't keep issues open that have been fixed.

I define 'fixed' as 'a resolution is available to the vast majority of users'. I'm on Ubuntu 22.04, likely the most popular Linux flavor and version, and the bubblewrap package is at 0.6.1 even when using the flatpak ppa. I would say that is not 'fixed' by my definition - I would have to seek out a ppa for bubblewrap (which there doesn't seem to be one) or build from scratch and hope it is the right version to coincide with the stable flatpak version. Simply suggesting the bleeding edge mainline has a fix doesn't constitute 'fixed' in my user-centric development model - it needs to be available in the stable build available to most users. And pushing the issue off to OS maintainers to update a critical dependency seems like a recipe for fixes not reaching most users in a timely fashion. To my understanding this is one of the fundamental problems flatpak is trying to solve, timely releases that avoid relying on a distro's package maintainers, yet seems to be occurring here. "Upgrade your entire OS or switch distros to get a upgraded dependency package for flatpak, or pester your distro maintainers" should not be a solution for almost any flatpak issue.

I will leave it at that for now as I already have a solution to this quagmire which is "find an alternative to flatpak when the symlink issue comes up". Just wanted to let the flatpak devs know that will be a likely route users will take when issues like this come up and they are marked as "fixed" when that isn't true for most users.

**Comment by C-512L** [comment]
> Thanks for the clarification.
> 
> This raises more questions that answers though - why is a critical dependency of flatpak like bubblewrap left up to OS maintainers? Shouldn't it be bundled into flatpak so they are built and released together? (As you say, that's how the flatpak git repo works with bubblewrap as a git submodule, I assumed they were released as such as well, but I was mistaken. I see other projects use bubblewrap as well, but I would suggest that they bundle their own bubblewrap versions rather than falling back to everyone sharing the same bubblewrap, or else flatpak itself not rely on the OS package and bundle its own bubblewrap.)
> 
> > bug trackers don't keep issues open that have been fixed.
> 
> I define 'fixed' as 'a resolution is available to the vast majority of users'. I'm on Ubuntu 22.04, likely the most popular Linux flavor and version, and the bubblewrap package is at 0.6.1 even when using the flatpak ppa. I would say that is not 'fixed' by my definition - I would have to seek out a ppa for bubblewrap (which there doesn't seem to be one) or build from scratch and hope it is the right version to coincide with the stable flatpak version. Simply suggesting the bleeding edge mainline has a fix doesn't constitute 'fixed' in my user-centric development model - it needs to be available in the stable build available to most users. And pushing the issue off to OS maintainers to update a critical dependency seems like a recipe for fixes not reaching most users in a timely fashion. To my understanding this is one of the fundamental problems flatpak is trying to solve, timely releases that avoid relying on a distro's package maintainers, yet seems to be occurring here. "Upgrade your entire OS or switch distros to get a upgraded dependency package for flatpak, or pester your distro maintainers" should not be a solution for almost any flatpak issue.
> 
> I will leave it at that for now as I already have a solution to this quagmire which is "find an alternative to flatpak when the symlink issue comes up". Just wanted to let the flatpak devs know that will be a likely route users will take when issues like this come up and they are marked as "fixed" when that isn't true for most users.

This is the upstream bug tracker. If you have an issue with how your distro packages flatpak/bwrap, please report them to your distro's package maintainers instead. This kind of messages waste other people and project developers's valuable time.

**Comment by RenanSantos7** [comment]
I'm on Fedora 40 with flatpak 1.15.8 and this issue still remain. I've switch Pictures page by a symlink to another path, and always I run Steam, this problem occurs. 

I have to recreate Pictures folder to "fix" it.

**Comment by C-512L** [comment]
> I'm on Fedora 40 with flatpak 1.15.8 and this issue still remain.

Fedora 40 still ships bwrap 0.8.0 (was fixed in 0.9.0). Please check `bwrap --version` version before reporting as not working.

**Comment by MoreDelay** [comment]
I just got the same issue on Fedora 40 with flatpak 1.15.10, bwrap 0.10.0.

```
$ flatpak run com.valvesoftware.Steam 
bwrap: Can't make symlink at /home/delay/Music: destination exists and is not a symlink
$ file ~/Music
/home/delay/Music: symbolic link to /media/hdd/Media/Music
$ flatpak --version
Flatpak 1.15.10
$ bwrap --version
bubblewrap 0.10.0
```

Not sure why it says the destination is not a symlink, because it is. Removing this link allows steam to run, creating it again makes this error appear again.

**Comment by chrisawi** [comment]
@MoreDelay I believe that error is from inside the sandbox namespace, so it's referring to `~/.var/app/com.valvesoftware.Steam/Music` on the host. That file apparently isn't a symlink; if you remove it, it should be recreated correctly.

I'd guess that you ran Steam with `--filesystem=~/Music` while `~/Music` was a directory, and so flatpak created a matching mountpoint directory inside the app data dir. Normally that directory would have been ephemeral, but Steam uses `--persist=.` to persist the entire home directory, so it also persists. This is an unfortunate interaction. It might be worth opening a new issue although I'm not sure how likely a fix is.

**Comment by MoreDelay** [comment]
Looks like you are right, that fixed the issue. I guess then that is an issue with the steam flatpak, not with flatpak itself. Thanks for helping me out. Although I would say the error message is wildly misleading so it is hard to figure this out yourself. I would never have guessed that an absolute path in a message is actually refering to somewhere else. But I suppose it can be difficult to make that clearer too due to the sandboxing and changing roots involved.

**Comment by rugk** [comment]
> I guess then that is an issue with the steam flatpak

So then please report it there: https://github.com/flathub/com.valvesoftware.Steam/issues/

**Comment by tadami98** [comment]
❯ flatpak run com.valvesoftware.Steam
bwrap: Can't make symlink at /home/tadami/Pictures: destination exists and is not a symlink

❯ rm -rf ~/.var/app/com.valvesoftware.Steam/Pictures/

This fixed the issue for me.

**Comment by rugk** [comment]
Hmm, is there a regression? In a new flatpak installation this again does not work anymore?

```console
$ flatpak --version                  
Flatpak 1.16.1
$ flatpak run com.valvesoftware.Steam 
bwrap: Can't make symlink at /var/home/rugk/Musik: destination exists and is not a symlink
$ ls -la /var/home/rugk/Musik                     
lrwxrwxrwx+ 1 rugk rugk 16 Sep 21 15:34 /var/home/rugk/Musik -> Nextcloud/Musik/
$ LANG=en flatpak info com.valvesoftware.Steam

Steam - Launcher for the Steam software distribution service

          ID: com.valvesoftware.Steam
         Ref: app/com.valvesoftware.Steam/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.0.84
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 60.0?MB
     Runtime: org.freedesktop.Platform/x86_64/25.08
         Sdk: org.freedesktop.Sdk/x86_64/25.08

      Commit: ac7e5fde7bf413de33cf972f274b16df591d2d44a9bb64e724bd2fb0aa6b2570
      Parent: 13210171b229ea0bc90c2c8d09327f6282a9d04ed727a1e19281847706a815c0
     Subject: Bump the note and enclose with double asterisk (a3688e6a32af)
        Date: 2025-10-02 14:54:45 +0000
```
