### ISSUE TITLE
Flatpak CLI installation spits weird characters upon completion

### ISSUE THREAD

**Issue by csoriano1618** [flatpak/flatpak#2712]
## Linux distribution and version
Fedora 30
## Flatpak version
1.2.3
## Description of the problem
Flatpak CLI installation spits weird characters upon completion. See screnshot:
![screenshot from 2019-02-21 11-14-08](https://user-images.githubusercontent.com/1755514/53161211-d3d28a80-35c9-11e9-8f99-be99b1d244d9.png)
## Steps to reproduce
Install several applications.

**Comment by matthiasclasen** [comment]
Please provide more detail. It clearly does not happen on every installation, or I would see it too.

**Comment by csoriano1618** [comment]
The command I ran was:

`flatpak install gnome-apps-nightly org.gnome.BoxesDevel org.gnome.Builder org.gnome.Calculator org.gnome.Calendar org.gnome.Devhelp org.gnome.Evince org.gnome.Epiphany org.gnome.GamesDevel org.gnome.FractalDevel org.gnome.Gitg org.gnome.Glade  org.gnome.Maps org.gnome.Photos org.gnome.Polari org.gnome.TodoDevel org.gnome.eog org.gnome.evince org.gnome.gedit org.gnome.gitgDevel -y`

Is there any other detail that would help?

**Comment by matthiasclasen** [comment]
Did you do anything while the command was running - hit backspace, type characters, etc ?

**Comment by csoriano1618** [comment]
Not really, that's the surprising part. This has happened in two different computers I installed f30 and did this command. The first time I also thought it was me pressing keys.

**Comment by mwleeds** [comment]
I just saw something similar:
```
0 ✓ mwleeds@pop-os ~/Desktop/flatpak ((HEAD detached at origin/master))* (2 keys)
↳ flatpak update
Looking for updates…
Required runtime for org.flatpak.Builder/x86_64/master (runtime/org.freedesktop.Sdk/x86_64/18.08) found in remote flathub
Do you want to install it? [Y/n]: 


        ID                                              Arch             Branch           Op           Remote                    Download
 1. [|] org.freedesktop.Sdk                             x86_64           18.08            i            flathub                     343.6 MB / 596.4 MB
 2. [ ] org.freedesktop.Sdk.Locale                      x86_64           18.08            i            flathub                   < 319.3 MB (partial)
 3. [ ] org.freedesktop.Platform.html5-codecs           x86_64           18.08            i            flathub                     < 2.9 MB
 4. [ ] org.gnome.Platform                              x86_64           master           u            gnome-nightly             < 379.1 MB
 5. [ ] org.gnome.Platform.Locale                       x86_64           master           u            gnome-nightly             < 327.3 MB (partial)
 6. [ ] org.gnome.Epiphany                              x86_64           master           u            epiphany-origin             < 4.7 MB
 7. [ ] org.gnome.Epiphany.Locale                       x86_64           master           u            epiphany-origin             < 2.1 MB (partial)

Updating 7/7… ████████████████████ 100%R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;61R^[[50;59R^[[50
;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;59R^[[50;40R^[[50;40R^[[50;40R^[[50;40R^[[50;40R^[[50;40R^[[50;51R^[[50;52R^[[50;52R^[[50;52R^[[50;52R^[[50;50R^[[50;50R^[[50;50R^[[50;40R^[[51;147R0 ✓ mwleeds@pop-os ~/Desktop/flatpak ((HEAD detached at origin/master))* (2 keys)
↳ R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;42R0;42R0;42R0;42R0;42R0;55R0;53R0;54R0;54R0;54R0;54R0;54R0;54R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;61R0;40R0;40R0;52R0;52R0;52R0;52R0;52R0;52R0;52R0;52R0;52R0;52R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;59R0;40R0;40R0;40R0;40R0;40R0;40R0;51R0;52R0;52R0;52R0;52R0;50R0;50R0;50R0;40R1;147R
```

**Comment by refi64** [comment]
Off the top of my head, I recall this happening once and I had to run `reset` to fix it, my best guess was that something else left the terminal in a weird state.

-- Ryan
https://refi64.com/

**Comment by sudoxey** [comment]
I'm sorry to necropost this but (3 years later), I ran into this same issue and can't figure out what's wrong.

Some weird random characters printed on my terminal (Ubuntu 22.04) when I was trying to install UngoogledChromium via bash script.

```
sudo apt update

sudo apt full-upgrade -y

sudo apt install -y flatpak

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install -y --noninteractive flathub com.github.Eloston.UngoogledChromium

mkdir -p "$HOME/.var/app/com.github.Eloston.UngoogledChromium/config"

tee "$HOME/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf" > /dev/null << EOF
--force-dark-mode
--enable-features=WebUIDarkMode
EOF

```

This bug has unprecedentedly terminated my bash script. Everything else after this stopped running (the script).

**Comment by Hasshu** [comment]
I just saw the terminal produce `;52R` after running `flatpak update && flatpak uninstall --unused`, and installing a couple updates. Something similar happened a few times in the past, though I have yet to see a pattern.

**Comment by AppleMayExist** [comment]
Is there any status on this? It seems to only happen when typing or (sometimes) when resizing the window. Application details stop updating, and the spinner stops as well.

**Comment by nekohayo** [comment]
I am most often (pretty much systematically) seeing the spurious characters being printed to the **powerline** commandline prompt when running `flatpak update`.

In my case today on Fedora 39, this is how I reproduced it:

1. Use a terminal (ptyxis, gnome-terminal, gnome-console), with [powerline](https://powerline.readthedocs.io/en/latest/overview.html) enabled  
(I used [this tutorial](https://fedoramagazine.org/add-power-terminal-powerline/) to set it up on Fedora; nothing out of the ordinary when it comes to using powerline.)
2. Run `flatpak update` _at a time where updates are available_
3. Apply the updates and wait for the progress indication to be completed

As a result, these spurious characters were inserted into the subsequent command prompt, just before the cursor: `;51R;40R;40R;40R;51R;40R;40R;40R;51R;40R;40R;40R;40R;51R;40R;40R;52R;52R;52R`

It looked like this today in Ptyxis after the `flatpak update` process completed:

![image](https://github.com/flatpak/flatpak/assets/479401/0d608a0e-6232-4508-942c-01cc0ca173c4)

Sometimes it might be a single `;51R` or `;40R` or something like that being printed, rather than a whole line of them.

I've _only_ seen this happen when running `flatpak update`, no other commandline app/command seems to do this (including dnf, wget, axel, etc.).

On another machine with gnome-console but _without_ powerline installed, the problem did not seem to occur this morning. It may be pure luck, or something else...

Some hypotheses that y'all might want to investigate:
* It may be easier to reproduce with powerline? (though it doesn't seem like others were using that necessarily)
* Could it have something to do with the terminal's zoom factor / font sizes?
* Could it be related to the terminal's window size? (I think it will particularly be sensitive to breaking flatpak if you resize it, though in the case at hand this morning I had not resized anything while running `flatpak update`)
* Could it have something to do with overlay scrollbars, or the scrollback size?
* Could it be due to the checkboxes not all being checked in the progress indication? Notice that all our outputs (mine, @mwleeds' and @csoriano1618's above) show the update being complete (ex: "Updating 7/7", "Updating 9/9", etc.) but the individual checkboxes above the finish line are _not_ all checked... this looks very suspicious to me.

**Comment by hfiguiere** [comment]
This is IMHO a Ptyxis bug. I have never seen it on GNOME Terminal put has a been doing it a lot on Ptyxis (or Prompt before).

**Comment by hfiguiere** [comment]
even though the OP seems contradict this (old bugs...)

**Comment by tibequadorian** [comment]
> This is IMHO a Ptyxis bug. I have never seen it on GNOME Terminal put has a been doing it a lot on Ptyxis (or Prompt before).

It happens for me on Konsole (KDE Terminal) too

**Comment by nekohayo** [comment]
I am now increasingly suspecting it has something to do with those "incomplete checkboxes" seen in the above outputs, as I previously theorized. When `flatpak update` ticks all the `[✓]` checkboxes to the end, there are no garbage characters being printed to the prompt after completion, at least from what I was able to see again just now, within the same terminal (Ptyxis, with Powerline). Other than that the only other things that may have changed would be the window size or that kind of thing.

**Comment by ciro-mota** [comment]
I have (perhaps partially) the same problem reported in this topic but I only notice it when performing update routines through the terminal.

Fedora 40.
flatpak-1.15.8-1.fc40.x86_64
Terminator.

![2024-06-14_14-39](https://github.com/flatpak/flatpak/assets/57502603/ad66c5e4-7342-4516-9f25-4d1a5664a19a)

**Comment by Trainmaster2** [comment]
I've also run into this issue, but only when running the commands from a script. Here's a recording of what I'm getting: https://asciinema.org/a/A0DxRGcgVucLMKD9RXKGZMpp7. While I'm using docker containers here, I've seen this same behavior in virtual machines.

Left pane: Flatpak commands run from script
Right pane: Flatpak commands run directly in terminal
Bottom pane: The aforementioned script

**Comment by timfenney** [comment]
Who's here in 2025? 🍾

**Comment by purpleidea** [comment]
> GNOME Terminal

@hfiguiere I see it all the time in GNOME Terminal. Fedora 42 and earlier.

![Image](https://github.com/user-attachments/assets/ead60e71-a77e-4a48-b85a-7436c44a7840)

**Comment by serial02** [comment]
The same thing happens here.

<img width="1161" height="248" alt="Image" src="https://github.com/user-attachments/assets/7239766e-7e1e-4947-ab38-b41eafa92dc6" />

**Comment by swick** [comment]
For anyone who can reliable reproduce the issue: please run `script --timing=flatpak-escape-issue.tm flatpak-escape-issue.log` then reproduce it, then `exit` and share the files.

**Comment by stuarthayhurst** [comment]
Is it possible that the command could suppress the issue? I've been doing all my `flatpak update` through it recently and I haven't had the issue. I've skipped maybe 4 or 5 times and had it occur twice on those.

**Comment by swick** [comment]
Well, could be possible, but that doesn't really help me with figuring out why this happens unfortunately.

**Comment by stuarthayhurst** [comment]
Fair enough, anecdotally it happens more often with longer installs / downloads, if that's any use

**Comment by stuarthayhurst** [comment]
Never mind, got it

<img width="945" height="746" alt="Image" src="https://github.com/user-attachments/assets/c655bd88-d615-4137-a89e-96490b5caaf2" />

Logs attached are for the output above

[flatpak-escape-issue.log.txt](https://github.com/user-attachments/files/26259934/flatpak-escape-issue.log.txt)
[flatpak-escape-issue.tm.txt](https://github.com/user-attachments/files/26259933/flatpak-escape-issue.tm.txt)

**Comment by swick** [comment]
@stuarthayhurst thanks a lot! `scriptreplay -m 1 -d 4 --timing=./flatpak-escape-issue.tm.txt ./flatpak-escape-issue.log.txt` is working well to reproduce this now.

**Comment by swick** [comment]
```
Updating 4/4… ESC[2m████████████████████ESC[22m 100%  127.7 MB/sESC[?25hESC[6n
^[[25;52RESC]666;vte.shell.postexec=0ESC\ESC]7;file://snakeroot/home/ratus5/DownloadsESC\ESC]0;ratus5@snakeroot:~/DownloadsESC\ESC]666;vte.shell.precmd!ESC\ESC[?2004hESC]0;ratus5@snakeroot: ~/Downloads^GESC[01;32mratus5@snakerootESC[00m:ESC[01;34m~/DownloadsESC[00m$ ^G;52R
```
We can see the Cursor Position command (`ESC[6n`) result getting echoed back to the terminal (`^[[25;52R`). Curiously there also is a newline. Somehow `flatpak_get_cursor_pos` failed to match on the result. Pressing enter, or any key really, at the right time can trigger the issue. So one issue is that we fail to properly match on the result, and one issue is that if we fail, we echo back the bytes which we failed to match.

So I think with https://github.com/flatpak/flatpak/pull/6549 the problem should be solved, but I would appreciate some testing.

**Comment by stuarthayhurst** [comment]
I don't remember pressing any extra keys, I started the update and swapped to another terminal tab.

I'll try to test that if I get some time, but that _might_ not be for a while.

**Comment by swick** [comment]
I'm not saying that you have to press keys to get the issue, it just makes it easy to reproduce the issue (or at least another very similar issue). There are other ways to get bytes into stdin.

**Comment by purpleidea** [comment]
Nice to see a patch! \o/

FWIW I see this fairly reliably and I never push keys, other than the initial enter to run a command and Y to accept changes.

**Comment by stuarthayhurst** [comment]
I'm still seeing this on 1.18.0:

<img width="1060" height="343" alt="Image" src="https://github.com/user-attachments/assets/590c685f-a2fe-4902-891d-8a3869a1dba2" />

**Comment by swick** [comment]
Not great. Get a terminal trace when you can reproduce it: https://github.com/flatpak/flatpak/issues/2712#issuecomment-3548954309

e: should have looked more closely. This is still the same Cursor Position command response.

**Comment by swick** [comment]
You could test if https://github.com/swick/flatpak/commits/wip/term-cursor-pos-improvement/ helps.

**Comment by stuarthayhurst** [comment]
> Not great. Get a terminal trace when you can reproduce it:

Sure, I'll update you when I get one

> You could test if https://github.com/swick/flatpak/commits/wip/term-cursor-pos-improvement/ helps.

It can take a very long time to reproduce this and other times it'll happen several times in a row, I might be able to try this in a VM but that would take even longer to try and reproduce it on

**Comment by stuarthayhurst** [comment]
Reproduced the bug with flatpak `1.18.2`, attached the outputs of the same capture script as before

[flatpak-escape-issue-logs.zip](https://github.com/user-attachments/files/31890445/flatpak-escape-issue-logs.zip)

While this time flatpak gave some (unrelated) warnings, those don't seem to be required to trigger the bug, I've had those warnings and the bug independently of each other

<img width="944" height="803" alt="Image" src="https://github.com/user-attachments/assets/d052eb7b-c9fb-4a64-a142-88cd3819dfee" />

**Comment by stuarthayhurst** [comment]
@swick Should this be reopened, or maybe a new issue filed?
