### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by konomikitten** [flatpak/flatpak#4571]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Debian

### Linux distribution version

Debian GNU/Linux 11 (bullseye)

### What architecture are you using?

x86_64

### How to reproduce

1. Install Firefox via Flatpak
2. Visit the GitHub website
3. Fonts used on GitHub look terrible

### Expected Behavior

For fonts to be rendered as the native version of Firefox does.

### Actual Behavior

The fonts on GitHub and some other websites look terrible.

### Additional Information

If I do the following work around fonts for Firefox are fixed but font settings won't be updated when my distribution updates them.

`cp /etc/fonts/conf.d/*.conf ~/.var/app/org.mozilla.firefox/config/fontconfig/conf.d/`

**Comment by vchernin** [comment]
What desktop environment/ window manager are you using?

**Comment by konomikitten** [comment]
Xfce 4.16/Xfwm4

**Comment by vchernin** [comment]
is `xdg-desktop-portal-gtk` installed (it should be), if so what version?

**Comment by konomikitten** [comment]
```
$ apt policy xdg-desktop-portal-gtk
xdg-desktop-portal-gtk:
  Installed: 1.8.0-1
  Candidate: 1.8.0-1
  Version table:
 *** 1.8.0-1 500
        500 https://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by tinywrkb** [comment]
Do you have `gsettings-desktop-schemas` installed? It should be a dependency of `xdg-desktop-portal-gtk`. If it's not being pulled-in as a dependency, then it's a Debian bug and should be reported.

**Comment by konomikitten** [comment]
```
$ apt policy gsettings-desktop-schemas
gsettings-desktop-schemas:
  Installed: 3.38.0-2
  Candidate: 3.38.0-2
  Version table:
 *** 3.38.0-2 500
        500 https://deb.debian.org/debian bullseye/main i386 Packages
        500 https://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by tinywrkb** [comment]
Oh! This is pre-Gnome 40.0 release, then you need to install also `gnome-settings-daemon`, as you need the XSETTINGS GSettings schema, which was only moved to `gsettings-desktop-schemas` in release 40.0.

The alternative is to copy the schema from `gnome-settings-daemon`, meaning the file `org.gnome.settings-daemon.plugins.xsettings.gschema.xml` and a proper edited `org.gnome.settings-daemon.enums.xml` (see [example](https://aur.archlinux.org/cgit/aur.git/tree/?h=gsettings-xsettings-schemas)), and then update the schema database by running something like `# glib-compile-schemas /usr/share/glib-2.0/schemas`.

**Comment by konomikitten** [comment]
> Oh! This is pre-Gnome 40.0 release, then you need to install also `gnome-settings-daemon`, as you need the XSETTINGS GSettings schema, which was only moved to `gsettings-desktop-schemas` in release 40.0.

Installed `gnome-settings-daemon` still not working. For reference:

Native:
![native](https://user-images.githubusercontent.com/12713710/143018596-4167cc34-766f-4929-8784-94860f9be0a9.png)

Flatpak:
![flatpak](https://user-images.githubusercontent.com/12713710/143018621-673208cf-758e-4f7b-8d9b-0decdcf8feec.png)

**Comment by tinywrkb** [comment]
Did you try to restart the system? Or at least `xdg-desktop-portal.service` and `xdg-desktop-portal-gtk.service`.

**Comment by konomikitten** [comment]
> Did you try to restart the system?

Same result.

XFCE does not start `GNOME Xsettings` as it uses it's own provider, I'm not sure if that matters though thought I'd ask?

**Comment by tinywrkb** [comment]
> XFCE does not start GNOME Xsettings as it uses it's own provider, I'm not sure if that matters though thought I'd ask?

No, you don't need the Gnome Settings daemon running.

> Same result.

I'm not sure what's going on. Maybe try restarting the portals manually from the command-line and look for errors. Something like

```
$ /usr/lib/xdg-desktop-portal -vr & /usr/lib/xdg-desktop-portal-gtk -vr
```

**Comment by konomikitten** [comment]
I've attached the output of both commands below, thanks for working on this.

[xdg-desktop-portal.txt](https://github.com/flatpak/flatpak/files/7587836/xdg-desktop-portal.txt)
[xdg-desktop-portal-gtk.txt](https://github.com/flatpak/flatpak/files/7587837/xdg-desktop-portal-gtk.txt)

**Comment by tinywrkb** [comment]
I'm not sure if this going to help, but `XDG_CURRENT_DESKTOP` is not set correctly by XFCE.  
Export `XDG_CURRENT_DESKTOP=XFCE:GNOME`, and then restart the portals.  
Also run the tested app with this variable updated.  

Note that some apps do not split on colon as expected, or have a bad implementation of a value matching logic, though from my experience they are very few, and it's easy to override the variable value for these apps with Flatpak.

Non-related, but clearly the Debian maintainer is wrong here for not including PipeWire as a runtime dependency of `xdg-desktop-portal`.

**Comment by konomikitten** [comment]
No luck with that screenshot below.

![XDG_CURRENT_DESKTOP](https://user-images.githubusercontent.com/12713710/143033153-44176d88-044a-4ae1-8f0d-2db3a5ee6e5f.png)

**Comment by konomikitten** [comment]
Also it seems XFCE does set it properly? In a fresh terminal:

```
$ set | grep ^XDG_CURRENT_DESKTOP
XDG_CURRENT_DESKTOP=XFCE
```

**Comment by tinywrkb** [comment]
> Also it seems XFCE does set it properly? In a fresh terminal:
> 
> ```
> $ set | grep ^XDG_CURRENT_DESKTOP
> XDG_CURRENT_DESKTOP=XFCE
> ```

XFCE does not provide XDG Portal implementations, so unless its developers don't care about their users and Flatpak, as a desktop environment it should set the GTK portal implementations correctly.  
This should be set explicitly and not rely on fallback behavior, which can change if another implementations is installed.

This means one of these two:

* Append `:GNOME` to `XDG_CURRENT_DESKTOP`.
* Add `xfce` to the `UsedIn` key in `/usr/share/xdg-desktop-portal/portals/gtk.portal`

I'm running Sway, and last time I tried, I still needed to add `:GNOME` to  `XDG_CURRENT_DESKTOP`. I don't remember the reason I had to keep it, as I had to deal with other issues.  

> No luck with that screenshot below.

Then I'm not sure what's going on, and I'm not using Debian.  
Wait for a response from a Flatpak dev or try reaching out via the Flatpak IRC or Matrix channel.  
You can also look in [this bug report](https://github.com/flatpak/flatpak/issues/2861), though I think I already covered all the workarounds.  
As this a distro (and distro release) specific, I suggest also reporting this on Debian bug system.

**Comment by smcv** [comment]
> Non-related, but clearly the Debian maintainer is wrong here for not including PipeWire as a runtime dependency of `xdg-desktop-portal`.

It's a Recommends (via the Pipewire client library), which is "a strong, but not absolute, dependency" and "would be found together with this one in all but unusual installations" (Debian Policy §7.2). If you don't install Recommends, then you can expect some features not to work, including major features.

**Comment by smcv** [comment]
> Append `:GNOME` to `XDG_CURRENT_DESKTOP`

That would not be true: XFCE is not a GNOME variant, and lots of things that would work in a GNOME session don't work in XFCE (in particular, various GNOME-specific portal implementations talk to GNOME Shell, but XFCE doesn't use GNOME Shell, so that can't work).

> Add `xfce` to the `UsedIn` key in `/usr/share/xdg-desktop-portal/portals/gtk.portal`

If XFCE developers want apps running on XFCE to use the `-gtk` backend, then the place to do that would be <https://github.com/flatpak/xdg-desktop-portal-gtk/pulls>.

However, if there is no backend that matches `UseIn`, then xdg-desktop-portal will fall back to trying *any* backend, ignoring `UseIn`. Currently it uses the first one in alphabetical order, which in practice means either `-gnome` or `-gtk`.

From the logs that @konomikitten provided, the `-gtk` backend is being used for the Settings portal, which is the one that's relevant for font antialiasing settings:

```
XDP: Using gtk.portal for org.freedesktop.impl.portal.Settings
XDP: providing portal org.freedesktop.portal.Settings
```

So changing `XDG_CURRENT_DESKTOP` or `UseIn` is not going to help: `gtk.portal` is already the one in use.

The next thing to check is the settings that `gtk.portal` will be providing to Flatpak apps. You can see all of them with:

```
dbus-send --print-reply \
--dest=org.freedesktop.impl.portal.desktop.gtk \
/org/freedesktop/portal/desktop \
org.freedesktop.impl.portal.Settings.ReadAll \
array:string:
```

The usual reason for "fonts look terrible" is antialiasing being disabled. The antialiasing setting is in the `org.gnome.desktop.interface` namespace:

```
method return time=1637757051.332628 sender=:1.1225 -> destination=:1.2208 serial=3647 reply_serial=2
   array [
      dict entry(
         string "org.gnome.desktop.interface"
         array [
...
            dict entry(
               string "font-antialiasing"
               variant                   string "rgba"
            )
...
```

What is that setting set to?

**Comment by smcv** [comment]
Other influential settings in `org.gnome.desktop.interface` include `font-hinting` and `font-rgba-order`.

In versions of GNOME before 40, font settings like those were in the `org.gnome.settings-daemon.plugins.xsettings` group, named `antialiasing`, `hinting` and `rgba-order`.

Unfortunately, which set of settings will actually be used depends on the version of GTK that is used by the specific Flatpak app you're using, and whether it's using X11 or Wayland. Most Flatpak apps use the version of GTK from the freedesktop.org SDK, but I think Firefox is special and might be using its own binary build of GTK.

**Comment by konomikitten** [comment]
> What is that setting set to?

Nothing it doesn't exist.

**Comment by konomikitten** [comment]
Also just a reminder for everyone the work around I found was:

`cp /etc/fonts/conf.d/*.conf ~/.var/app/org.mozilla.firefox/config/fontconfig/conf.d/` and this does fix the font looking horrid, so I'm not sure why we're looking at a bunch of GTK settings.

**Comment by konomikitten** [comment]
I decided to go have a poke around the GitLab for XFCE, is this issue helpful at all for this situation? https://gitlab.xfce.org/xfce/xfce4-settings/-/issues/179

**Comment by konomikitten** [comment]
I don't intend to keep the work around I just went back to native Firefox for now, I'll probably wait awhile and come back around to Flatpak or maybe try it again at some stage if I am not using XFCE.

Thanks everyone for all the help.

**Comment by behrmann** [comment]
> Also just a reminder for everyone the work around I found was:
> 
> `cp /etc/fonts/conf.d/*.conf ~/.var/app/org.mozilla.firefox/config/fontconfig/conf.d/` and this does fix the font looking horrid, so I'm not sure why we're looking at a bunch of GTK settings.

As a more minimal workaround, you basically only need `/usr/share/fontconfig/conf.avail/70-no-bitmaps.conf`.

**Comment by baarkerlounger** [comment]
> `cp /etc/fonts/conf.d/*.conf ~/.var/app/org.mozilla.firefox/config/fontconfig/conf.d/`

I had the same issue with plain Gnome 42, Wayland, Debian 11 and this works for me also.

**Comment by dominiksr** [comment]
yessss!!! working for Debian testing, Gnome 43, Wayland

**Comment by mochaaP** [comment]
@smcv:
> Your workaround relies on the version of fontconfig on your host system being "compatible enough" with the version in the Flatpak sandbox, which might be true today, but will not stay true forever.

This introduced another issue:

Non-latin (especially CJK) languages' font packages usually include a fontconfig to ensure font fallback and locale-specific variant configurations are applied to work as expected. ([Example from Arch Linux `noto-fonts-cjk`](https://github.com/archlinux/svntogit-packages/blob/packages/noto-fonts-cjk/repos/extra-any/70-noto-cjk.conf))

With the current behavior, it's *very likely* for users of those locales have a broken font rendering e.g. Using bitmap fonts or low quality fonts instead of the supplied one / Inconsistent font family and/or wrong locale-specific glyph on the same text element.

Also, some users bind their generic font family names (`sans`, `serif`, `system-ui`, `emoji`) to alternative fonts (take [mine](https://fars.ee/O27X/xml/html?style=solarized-light) as an example), this results in an inconsistent look between native apps and sandboxed apps.

As stated above and based on the current situation, I suggest to reconsider the solution on fontconfig.

**Comment by dominiksr** [comment]
One user on reddit recommended to remove the metapackages xfonts-100dpi and xfont-75dpi and it works. 

https://www.reddit.com/r/flatpak/comments/g1owya/comment/i1ktj2t/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by jasongodev** [comment]
> One user on reddit recommended to remove the metapackages xfonts-100dpi and xfont-75dpi and it works.
> 
> https://www.reddit.com/r/flatpak/comments/g1owya/comment/i1ktj2t/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

I confirm this is the ONLY correct solution to this issue. I will explain in another comment thread.

**Comment by jasongodev** [comment]
### **The only correct solution to this issue is to remove x11 fonts.** 

This issue occurs mostly in Debian and openSUSE based distros with x11 fonts installed. Fedora and RHEL-based distros are usually not affected by default.

The issue happens due to the following:

1. When flatpak apps loads, it will prioritize the system fonts installed in the host.
2. If the font is not found in the system, it will look at the user font configuration and font files.
3. If the font is still not found in the user space, the aliases for fonts will kick in. As long as there is an equivalent family of the target font, it will use that font.

For example, in a Wikipedia webpage, the title of the topic uses 'Linux Libertine', 'Georgia', 'Times', serif; in that order. In default Debian and openSUSE installation Linux Libertine and Georgia are not installed. The next candidate is Times which is provided by an old x11 bitmap font. In Fedora, Times as x11 font is not present, therefore it fallbacks to serif which the flatpak runtime environment provides as TeX Gyre Termes.

What we need is to remove x11 fonts so we can have that fallback mechanism just like with other distros.

**In Debian remove x11 fonts using:**
```
sudo apt remove xfonts-base xfonts=100dpi xfonts-75dpi xfonts-base
```

In openSUSE based distros, use this code:
```
sudo zypper remove xorg-x11-fonts xorg-x11-fonts-legacy
```

**Comment by sandikata** [comment]
In Debian remove x11 fonts using:

sudo apt remove xfonts-base xfonts-100dpi xfonts-75dpi

This is about to remove task-desktop, xorg x11-session-utils, x11-apps and so on and so on.
Is it there any way to avoid such Debian behavior ?

**Comment by dominiksr** [comment]
> In Debian remove x11 fonts using:
> 
> sudo apt remove xfonts-base xfonts-100dpi xfonts-75dpi
> 
> This is about to remove task-desktop, xorg x11-session-utils, x11-apps and so on and so on. Is it there any way to avoid such Debian behavior ?

Some of these packages are meta packages. I have Debian 12 gnome/debian 12 testing gnome on several devices and have had no problems on wayland. If you are afraid and don't want to do this you can try the other solutions listed above.

Such as:

> Also just a reminder for everyone the work around I found was:
> 
> `cp /etc/fonts/conf.d/*.conf ~/.var/app/org.mozilla.firefox/config/fontconfig/conf.d/` and this does fix the font looking horrid, so I'm not sure why we're looking at a bunch of GTK settings.

**Comment by jeffcutsinger** [comment]
Currently running Cinnamon/Wayland on Debian bookworm, and also had this issue. If I recall correctly, the issue was also present in plain Gnome. Native firefox on this setup did not have this issue.

I removed `xfonts-base` and `xfonts-100dpi` (`xfonts-75dpi` was already not installed), and that did not work. Based on the reasoning of missing Georgia/other MS fonts I tried installing `ttf-mscorefonts-installer`, and that also did not work.

I ended up using a variant of the solution proposed by @behrmann. `fontconfig/conf.d` did not exist in `~/.var/app/org.mozilla.firefox/config`. `/etc/fonts/conf.d/70-no-bitmaps.conf` was a symlink to `/usr/share/fontconfig/conf.avail/70-no-bitmaps.conf`, and there was no `/etc/fonts/conf.avail/70-no-bitmaps.conf`.

```
mkdir -p ~/.var/app/org.mozilla.firefox/config/fontconfig/conf.d
cp /etc/fonts/conf.d/70-no-bitmaps.conf ~/.var/app/org.mozilla.firefox/config/fontconfig/conf.d
```

Fonts now look normal.

**Comment by dominiksr** [comment]
On debian next/testing (trixie) this problem no longer exists. 
Firefox 117.0 flatpak, wayland session.

If I have time later I will still check on a fresh install of debian 12.1.

**Comment by antistress** [comment]
> On debian next/testing (trixie) this problem no longer exists. Firefox 117.0 flatpak, wayland session.
> 
> If I have time later I will still check on a fresh install of debian 12.1.

Wow, indeed, I'm surprised and it must be quite new !
I'm running Debian GNU/Linux Testing with GNOME-Wayland & Firefox 117.0 flatpak and I can confirm that bug seems to have disappeared.
I would be curious to know the reason but I'm glad of the result !

**Comment by dominiksr** [comment]
Interestingly, this problem still exists in opensuse thumbleweed.

**Comment by dominiksr** [comment]
Ok debian 12.1 continues to have this problem then I don't know if this problem can be closed but it is good that it is finally solved in debian next.

**Comment by Zeitsperre** [comment]
Was seeing the same thing on Void Linux with KDE. Installing `xdg-desktop-portal` from the main void repositories did the trick for most flatpak applications (huzzah!), but the `flatseal` app still has some of the worst font aliasing I have ever seen. 

Not a major distraction as that app gets rarely used in my case, but odd that the issue remains.

**Comment by morganist** [comment]
bug fixed in KDE Plasma 5.27.9:
https://bugs.kde.org/show_bug.cgi?id=474746
https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/231
https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/233

**Comment by vinylen** [comment]
> Interestingly, this problem still exists in opensuse thumbleweed.

Can confirm as of nov 7/2023. Solved it by adding this line to `~/.var/app/org.mozilla.firefox/config/fontconfig/fonts.conf`

`<?xml version='1.0'?> <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'> <fontconfig>     <!-- Disable bitmap fonts. -->     <selectfont><rejectfont><pattern>         <patelt name="scalable"><bool>false</bool></patelt>     </pattern></rejectfont></selectfont> </fontconfig> `

**Comment by pingouyn** [comment]
In Plasma 5.27.8 I believe you can simply use Flatseal to disable the "socket=wayland" for any  needed application and it will revert back to x11 fonts.  It solved the issue for me with Parabole/Flatseal/Warpinator.  It's neat and reversible any time Plasma 5.27.9 drops.

**Comment by yozachar** [comment]
> In openSUSE based distros, use this code:
>
> ```
> sudo zypper remove xorg-x11-fonts xorg-x11-fonts-legacy
> ```


This: https://github.com/flatpak/flatpak/issues/4571#issuecomment-1606258732 works!

> _Man I wish, GitHub had some "bookmark comment" feature._

**Comment by foegra** [comment]
> ### **The only correct solution to this issue is to remove x11 fonts.**
> 
> This issue occurs mostly in Debian and openSUSE based distros with x11 fonts installed. Fedora and RHEL-based distros are usually not affected by default.
> 
> The issue happens due to the following:
> 
>     1. When flatpak apps loads, it will prioritize the system fonts installed in the host.
> 
>     2. If the font is not found in the system, it will look at the user font configuration and font files.
> 
>     3. If the font is still not found in the user space, the aliases for fonts will kick in. As long as there is an equivalent family of the target font, it will use that font.
> 
> 
> For example, in a Wikipedia webpage, the title of the topic uses 'Linux Libertine', 'Georgia', 'Times', serif; in that order. In default Debian and openSUSE installation Linux Libertine and Georgia are not installed. The next candidate is Times which is provided by an old x11 bitmap font. In Fedora, Times as x11 font is not present, therefore it fallbacks to serif which the flatpak runtime environment provides as TeX Gyre Termes.
> 
> What we need is to remove x11 fonts so we can have that fallback mechanism just like with other distros.
> 
> **In Debian remove x11 fonts using:**
> 
> ```
> sudo apt remove xfonts-base xfonts-100dpi xfonts-75dpi
> ```
> 
> **In openSUSE based distros, use this code:**
> 
> ```
> sudo zypper remove xorg-x11-fonts xorg-x11-fonts-legacy
> ```

Thank You!

**Comment by CaptainCoward** [comment]
> The only correct solution to this issue is to remove x11 fonts.

I have this issue on Arch. And removing the x11 fonts sounds a bit "extreme" i mean what if you have to switch to x11 for a certain app?
So far the only solution i found is running an app with the `GSK_RENDERER=gl `

**Comment by konomu** [comment]
I ran into this issue on Ubuntu 22.04 after switching from snap to flatpak Firefox.

**Comment by bbhtt** [comment]
> As a more minimal workaround, you basically only need `/usr/share/fontconfig/conf.avail/70-no-bitmaps.conf`.

This should be fixed since in at least in the fdsdk (since 25.08), gnome (since 49) and kde (since 6.10 and 5.15-25.08) runtimes which will have bitmap fonts blocked https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/eab3e094c619ab0b05cdca551288cd1b5458e21d

> I think the problem here might be similar to https://gitlab.xfce.org/xfce/xfce4-settings/-/issues/179, although not 100% the same (different settings keys are involved).
> https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/231
> https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/233

These were also fixed.

Closing this.
