### ISSUE TITLE
Vulkan not working on new AMD GPUs?

### ISSUE THREAD

**Issue by brodclaw** [flatpak/flatpak#6159]
I have been using nvidia gpu for few years now on flatpak without issues, few days ago got myself AMD RX 9070, but now most, if not all flatpak apps seem like they use integrated GPU instead of dedicated one, and don't support Vulkan?

If I try to specify GPU with "DRI_PRIME" it ends up using either llvmpipe or integrated GPU.

I am not sure if this is because drivers are not fully ready for the new GPU, if flatpak mesa drivers are still behind?

I am on Fedora 41 kernel version **6.13.6-200.fc41.x86_64 (64-bit)**, and apparently I have mesa 25.0.1 drivers installed. Flatpak beta offers 25.0.8 and I tried installing it, doesn't work. Apps still use 24.3.4.

I have these installed, version 24.3.4 apparently, from branch 23.08 and 24.08.

![Image](https://github.com/user-attachments/assets/37052313-8aa3-4e30-919a-a0470d48d8df)
![Image](https://github.com/user-attachments/assets/1ca4126d-b935-48e0-8785-fbbff1bfa538)

Also, I have tried installing Lutris using DNF, Vulkan drivers there seem to be loaded fine?

![Image](https://github.com/user-attachments/assets/4e8b6235-0330-40e6-94d7-3564313574a9)
![Image](https://github.com/user-attachments/assets/52f84b46-9554-4848-be99-c163ccbeb729)

Can I force apps to use mesa 25.0.8beta from flatpak-beta until this gets sorted out?

**Comment by chrisawi** [comment]
Flatpak apps cannot use mesa from the host, so this is the expected behavior, unfortunately. Mesa hasn't yet been updated in the 24.08 GL extension due to a [regression in mesa](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/25194) (most of the links in that MR won't work right now because fdo gitlab is in the middle of migration to a new host). It will be upgraded at some point, and probably 23.08 as well.

In the meantime, you can use the mesa-git extension: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/wikis/mesa-git

**Comment by brodclaw** [comment]
I tried running Lutris with "FLATPAK_GL_DRIVERS=mesa-git" after installing it from beta branch 25.08beta and it doesn't recognize any gpu at all.

![Image](https://github.com/user-attachments/assets/294e0899-317b-4567-87ae-3943bcf9a0bc)

**Comment by dan0v** [comment]
This might be unrelated, but after updating to kernel `6.13.6-200.fc41.x86_64`, my AMD GPU (Radeon RX 7700S) stopped working and all rendering (and ROCm) workloads were running on iGPU instead, with the dGPU just sitting there looking pretty - detected by the system, but the drivers not correctly loaded. After installing `6.13.7-200.fc41.x86_64` today, the issue is resolved.

**Comment by brodclaw** [comment]
> This might be unrelated, but after updating to kernel `6.13.6-200.fc41.x86_64`, my AMD GPU (Radeon RX 7700S) stopped working and all rendering (and ROCm) workloads were running on iGPU instead, with the dGPU just sitting there looking pretty - detected by the system, but the drivers not correctly loaded. After installing `6.13.7-200.fc41.x86_64` today, the issue is resolved.

I just updated to new kernel, still doesn't work even with mesa-git.

**Comment by brodclaw** [comment]
Recent update seems to have fixed this issue, Lutris and GPU Viewer detect my dGPU fine now.

![Image](https://github.com/user-attachments/assets/5c9cfdd1-d2a0-476d-bcc2-5271c86809ee)
![Image](https://github.com/user-attachments/assets/2b9915a0-0f7e-4e73-83ed-0513d210a299)
