### ISSUE TITLE
"Can't make symlink" error on build

### ISSUE THREAD

**Issue by alexschoeberl** [flatpak/flatpak#959]
I'm using Flatpak 0.9.5 on Endless OS. I'm running the following basic commands to build an app from my home directory:

    flatpak build-init hello-flatpak com.test.Hello org.gnome.Sdk org.gnome.Platform 3.22
    flatpak build hello-flatpak mkdir -p /app/Hello
    flatpak build hello-flatpak mkdir -p /app/bin

At the second `mkdir` command, I get the following error:

    Can't make symlink at /var/home: File exists

From now on, the error appears on every build command I use.

**Comment by alexlarsson** [comment]
Yeah, this sems to be some kind of symlink related issue, I was able to reproduce with the following:
/other-home == symlink to  var/home
/var/home == symlink to ../home
/home/$user == actual home directory

Which i believe is similar to the endless setup

**Comment by mwleeds** [comment]
I can reproduce this in EOS 3.2 but not in the EOS 3.3 beta release (running flatpak 0.9.8). So it was either fixed in flatpak or something else changed. I'll see if I can figure out why.

**Comment by Firstyear** [comment]
@mwleeds Do you know when the updated flatpak version will land in f27 atomic to see if this is resolved for AtomicWorkstation users? 

Thanks!

**Comment by mwleeds** [comment]
@Firstyear I'm not sure. Maybe @amigadave would be a better person to ask

**Comment by amigadave** [comment]
@Firstyear flatpak-0.10.2.1-1.fc27 has been stable in Fedora 27 for 2 weeks. Issue #1278 seems to suggest that the bug is not fixed in 0.10.2, but maybe 0.10.2.1 fixed it.

**Comment by alexlarsson** [comment]
I believe this is fixed by https://github.com/flatpak/flatpak/pull/1421

**Comment by XWarzor** [comment]
I have similar issue:
☣ flatpak run com.valvesoftware.Steam
bwrap: Can't make symlink at /home/xwarzor/Musique: File exists

My ~/Musique folder is linked to a Musique folder on my other hdd
flatpak v 0.99.3

**Comment by ioogithub** [comment]
I have this issue as well. I tried to install com.valvesoftware.Steam
bwrap: Can't make symlink at /home/oem/Music: File exists

I can't even uninstall it:
flatpak run com.valvesoftware.Steam --reset
bwrap: Can't make symlink at /home/oem/Music: File exists

**Comment by mwleeds** [comment]
@ioogithub it would be helpful if you mention what version of Flatpak you're using, the output of `flatpak --version`

**Comment by hfiguiere** [comment]
> I believe this is fixed by #1421

closing then.


The subsequent comments are unrelated and are #2387
